/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TemaTest;

public class App {
    
public App() {/* compiled code */}

    public static void main(java.lang.String[] strings) {
        System.out.print("Hello world!");
    }
}