/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TemaTest;

import TemaTest.Comment.CommentPost;
import TemaTest.Comment.DeleteComment;
import TemaTest.Comment.LikeComm;
import TemaTest.Comment.UnlikeComm;
import TemaTest.CommonUse.CleanupAll;
import TemaTest.CommonUse.Command;
import TemaTest.Posts.*;
import TemaTest.User.*;

import java.util.HashMap;
import java.util.Map;

public class App {
    private static final Map<String, Command> COMMANDS = new HashMap<>();

    static {
        COMMANDS.put("create-user", new CreateUser());
        COMMANDS.put("create-post", new CreatePost());
        COMMANDS.put("cleanup-all", new CleanupAll());
        COMMANDS.put("delete-post-by-id", new DeletePost());
        COMMANDS.put("follow-user-by-username", new FollowByUsername());
        COMMANDS.put("unfollow-user-by-username", new UnfollowByUsername());
        COMMANDS.put("like-post", new LikePost());
        COMMANDS.put("unlike-post", new UnlikePost());
        COMMANDS.put("like-comment", new LikeComm());
        COMMANDS.put("unlike-comment", new UnlikeComm());
        COMMANDS.put("get-followings-posts", new GetPostsFollowing());
        COMMANDS.put("get-user-posts", new GetUsersPosts());
        COMMANDS.put("get-post-details", new GetPostsDetails());
        COMMANDS.put("comment-post", new CommentPost());
        COMMANDS.put("delete-comment-by-id", new DeleteComment());
        COMMANDS.put("get-following", new GetFollowing());
        COMMANDS.put("get-followers", new GetFollowers());
        COMMANDS.put("get-most-liked-posts", new GetMostLikedPosts());
        COMMANDS.put("get-most-commented-posts", new GetMostCommentedPosts());
        COMMANDS.put("get-most-followed-users", new GetMostFollowedUsers());
        COMMANDS.put("get-most-liked-users", new GetMostLikedUsers());
    }

    public static void main(String[] strings) {
            if (strings == null) {
                System.out.println("Hello world!");
                return;
            }

        String commandName = strings[0].replaceFirst("-", "");
        Command command = COMMANDS.get(commandName);

        if (command != null) {
            command.execute(strings);
        }
    }
}